# --- General options --- #
# Theme of the website, to stay updated.
remote_theme: daattali/beautiful-jekyll@4.0.1
# Name of website
title: Shreyas Havaldar

# Short description of your site
description: Here is the virtual version of me.

# Name
author: Shreyas Havaldar

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Projects: "https://github.com/ShreyasHavaldar7"
  Curriculum Vitae: "https://drive.google.com/file/d/1MQU94ncaW1A0NxmPXRYUwQ8MqCPkQUV4/view?usp=sharing"
  Blog: "blog"
  Recommendations: "books"


# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/assets/img/dp.jpg"
# By default, the image is cut into a circle. You can disable this behaviour here.
# round-avatar: true

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
title-img: "/assets/img/dp.jpg"

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#99cbe8"
navbar-text-col: "#3e6fb6"
navbar-children-col: "#a8eff0"
page-col: "#f0f7f7"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#99cbe8"
footer-text-col: "#3e6fb6"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/bg_main.jpeg"
# footer-img: "/img/bg_main.jpeg"
# page-img: "/img/big_bg.svg"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
social-network-links:
  rss: true
  email: "shreyashavaldar@gmail.com"
  # facebook: deanattali
  github: ShreyasHavaldar7
  # twitter: daattali
  linkedin: shreyas-havaldar-71377b182
  # stackoverflow: "3943160/daattali"
#  reddit: yourname
#  xing: yourname
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
#  github: true
#  email: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
#url-pretty: "MyWebsite.com"  # eg. "deanattali.com/beautiful-jekyll"

# Create a "tags" index page and make tags on each post clickable
link-tags: true
# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-161728691-1"

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
# disqus: ""

# If you want to use JustComments fill with the API Key
#just-comments: "ABCD-EFGH-IJKL"

# To use Facebook Comments, fill in a Facebook App ID
# fb_comment_id: ""

# # To use Staticman comments, fill in repository, branch, and endpoint
# staticman:
#   repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
#   branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
#   endpoint   : # URL of your own deployment, with a trailing slash (will fallback to a public GitLab instance) eg. https://<your-api>/v3/entry/github/
#   reCaptcha:
#     # reCaptcha for Staticman (OPTIONAL, but recommended for spam protection)
#     # If you use reCaptcha, you must also set these parameters in staticman.yml
#     siteKey  : # Use your own site key, you need to apply for one on Google
#     secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format
date_format: "%B %-d, %Y"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Asia/Kolkata"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: true # add estimated reading time on all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  - docs/

paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

